test:
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: 0.0.0.0
  port: 5432
  database: vmt_test
  username: postgres
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: 0.0.0.0
  port: 5432
  database: vmt_development
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: 0.0.0.0
  port: 5432
  database: vmt_production
  username: postgres
  password: postgres

